
-- 10장
-- INSERT 문 : 테이블에 데이터를 추가 
-- 컬럼명 다 안 적어도 됨 

-- INSERT INTO
-- VALUES


-- 1. DEPT_TEMP //////////////////////////////////////////////
-- DEPT_TEMP 테이블 복사 생성 
CREATE TABLE DEPT_TEMP
    AS SELECT * FROM DEPT;

-- 데이터 추가
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES (50, 'DATABASE', 'SEOUL');

-- 오류들
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES (60, 'NETWORK');
-- VALUES 갯수 안 많음
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES (60, 'NETWORK', 'BUSAN', 'WRONG');
-- 문자형태문제
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES ('WRONG', 'NETWORK', 'BUSAN');
-- 자리수문제
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES (600, 'NETWORK', 'BUSAN');

-- 데이터 추가
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES (70, 'WEB', NULL);
-- 데이터 추가
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES (80, 'MOBILE', 'NULL');
-- 데이터 추가
INSERT INTO DEPT_TEMP (DEPTNO,  LOC)
VALUES (90, 'INCHEON'); 

-- DEPTNO 70이 두개 들어갔다
-- 하나만 삭제 안되나?
-- 중복을 합쳐줄 방법은??

-- 테이블 확인
SELECT * FROM DEPT_TEMP;



-- 2. EMP_TEMP //////////////////////////////////////////////
-- EMP_TEMP 빈공간 만들기
CREATE TABLE EMP_TEMP
AS SELECT *
FROM EMP
WHERE 1 <> 1;

-- 데이터 추가
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (2111, '이순신', 'MANAGER', 9999, TO_DATE('08/07/2026', 'DD/MM/YYYY'), 4000, NULL, 20);

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (3111, '심청이', 'MANAGER', 9999, SYSDATE, 4000, NULL, 30);

-- 서브쿼리를 이용해서 한번에 여러데이터 추가
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
    FROM EMP E, SALGRADE S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
    AND S.GRADE = 1
;
-- 테이블 확인
SELECT * FROM EMP_TEMP;


-- MERGE문 
-- 참고내용
MERGE INTO Target_Table T
USING Source_Table S
ON (T.Key_Column = S.Key_Column) -- 조인 조건
WHEN MATCHED THEN -- 데이터가 존재하면 (UPDATE)
UPDATE SET T.Column1 = S.Column1, ...
WHEN NOT MATCHED THEN -- 데이터가 존재하지 않으면 (INSERT)
INSERT (Key_Column, Column1, ...)
VALUES (S.Key_Column, S.Column1, ...);

-- 3. DEPT_TEMP2 //////////////////////////////////////////////
-- DEPT_TEMP2 테이블 복사 만들기
CREATE TABLE DEPT_TEMP2
AS SELECT *
FROM DEPT; 

-- 데이터 수정
-- 컬럼 LOC 전체가 바뀜
UPDATE DEPT_TEMP2
SET LOC = 'SEOUL'; 

-- 되돌린다. 어디까지?
ROLLBACK;
-- 적용한다
COMMIT;
-- 수정
UPDATE DEPT_TEMP2
SET DNAME = 'DATABASE',
    LOC   = 'SEOUL'
WHERE DEPTNO = 40    
; 
-- 조건 수정
UPDATE DEPT_TEMP2
SET (DNAME, LOC) = (SELECT DNAME, LOC
                    FROM DEPT
                    WHERE DEPTNO = 40  
                    ) 
WHERE DEPTNO = 40    
;  
-- 테이블 확인
SELECT * FROM DEPT_TEMP2;


-- 서브쿼리
-- 실행해보자 하고 롤백하면 됨///////////////
UPDATE DEPT_TEMP2
SET LOC = 'SEOUL'
WHERE DEPTNO = (SELECT DEPTNO
                FROM DEPT_TEMP2
                WHERE DNAME = 'OPERATIONS'
               )
;  
-- 실행해보자 하고 롤백하면 됨/////////////////
UPDATE DEPT_TEMP2
SET LOC = 'SEOUL'
WHERE DEPTNO IN (SELECT DEPTNO
                FROM DEPT_TEMP2
                WHERE DEPTNO IN (10, 20) 
               )
;  

CREATE TABLE EMP_TEMP2
AS SELECT * FROM EMP;



SELECT * 
FROM EMP_TEMP2
WHERE JOB = 'MANAGER';

DELETE FROM EMP_TEMP2
WHERE JOB = 'MANAGER'; 

-- //////////////////////////왜 안되지?
-- DELETE FROM EMP_TEMP2
-- WHRER EMPNO IN (SELECT E.EMPNO
--                 FROM EMP_TEMP2 E, SALGRADE S
--                 WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
--                 AND S.GRADE = 3
--                 AND DEPTNO = 30
--             )
-- ; 
SELECT * FROM EMP_TEMP2;
-- 전체삭재 해봐야함////////////////////////

-- 되새김문제 273P
CREATE TABLE CHAP10HW_EMP
AS SELECT * FROM EMP;
CREATE TABLE CHAP10HW_DEPT
AS SELECT * FROM DEPT;
CREATE TABLE CHAP10HW_SALGRADE
AS SELECT * FROM SALGRADE;

SELECT * FROM CHAP10HW_EMP;
SELECT * FROM CHAP10HW_DEPT;
SELECT * FROM CHAP10HW_SALGRADE;

-- INSERT INTO (컬럼명, 컬럼명)
-- VALUES (값, 값);

-- INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC)
-- VALUES (50, 'ORACLE', 'BUSAN');
-- INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC)
-- VALUES (60, 'SQL', 'ILSAN');
-- INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC)
-- VALUES (70, 'SELECT', 'INCHEON');
-- INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC)
-- VALUES (80, 'DML', 'BUNDANG');  

INSERT INTO CHAP10HW_DEPT VALUES (50, 'ORACLE', 'BUSAN');
INSERT INTO CHAP10HW_DEPT VALUES (60, 'SQL', 'ILSAN');
INSERT INTO CHAP10HW_DEPT VALUES (70, 'SELECT', 'INCHEON');
INSERT INTO CHAP10HW_DEPT VALUES (80, 'DML', 'BUNDANG'); 

-- INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC)
-- VALUES (50, 'ORACLE', 'BUSAN'), 
-- VALUES (60, 'SQL', 'ILSAN'), 
-- VALUES (70, 'SELECT', 'INCHEON'), 
-- VALUES (80, 'DML', 'BUNDANG');





-- 유진씨꺼 복사함
-- INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
-- VALUES (7201, 'TEST_USER1', 'MANAGER', 7788, TO_DATE('16/01/02','YY/MM/DD'), 4500, NULL, 50);
INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7202, 'TEST_USER2', 'CLERK', 7201, TO_DATE('16/02/21','YY/MM/DD'), 1800, NULL, 50);
INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7203, 'TEST_USER3', 'ANALIST', 7201, TO_DATE('16/04/11','YY/MM/DD'), 3400, NULL, 60);
INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7204, 'TEST_USER4', 'SALESMAN', 7201, TO_DATE('16/05/31','YY/MM/DD'), 2700, 300, 60);
INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7205, 'TEST_USER5', 'CLERK', 7201, TO_DATE('16/07/20','YY/MM/DD'), 2600, NULL, 70);
INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7206, 'TEST_USER6', 'CLERK', 7201, TO_DATE('16/09/08','YY/MM/DD'), 2600, NULL, 70);
INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7207, 'TEST_USER7', 'LECTURER', 7201, TO_DATE('16/10/28','YY/MM/DD'), 2300, NULL, 80);
INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7208, 'TEST_USER8', 'STUDENT', 7201, TO_DATE('18/03/09','YY/MM/DD'), 1200, NULL, 80);


-- 내가 하나만 해보기
INSERT INTO CHAP10HW_EMP VALUES ('7201','TEST_USER1','MANAGER',7788,TO_DATE('16/01/02','YY/MM/DD'),1300,NULL,50); 

-- Q3
UPDATE CHAP10HW_EMP
SET DEPTNO = 70
WHERE SAL > (SELECT AVG(SAL)
                FROM CHAP10HW_EMP
                WHERE DEPTNO = 50
                )
;

-- Q4
UPDATE CHAP10HW_EMP
SET
;

UPDATE CHAP10HW_EMP
SET DEPTNO = 60
WHERE ENAME = 'TEST_USER3'
;
UPDATE CHAP10HW_EMP
SET DEPTNO = 60
WHERE ENAME = 'TEST_USER4'
;
SELECT *  FROM CHAP10HW_EMP
WHERE ENAME = 'TEST_USER3';


-- 267P
-- UPDATE CHAP10HW_EMP
-- SET SAL = (SELECT SAL + SAL*0.1 
--             FROM CHAP10HW_EMP
--             WHERE HIREDATE > (SELECT MIN(HIREDATE)
--                                 FROM CHAP10HW_EMP
--                                 WHERE DEPTNO = 60
--                             )  
--              ),
--     DEPTNO = 80
-- WHERE DEPTNO = 60
-- ;             
-- //////////////////////////////////////// 확인해보자
UPDATE CHAP10HW_EMP
SET SAL = SAL + SAL*0.1, DEPTNO = 80
WHERE DEPTNO = 60
AND HIREDATE > (SELECT MIN(HIREDATE)
                    FROM CHAP10HW_EMP
                    WHERE DEPTNO = 60
                )   
;   


SELECT * 
FROM CHAP10HW_EMP 
WHERE DEPTNO = 80
AND HIREDATE > (SELECT MIN(HIREDATE)
                    FROM CHAP10HW_EMP
                    WHERE DEPTNO = 80
                )   
ORDER BY HIREDATE;

-- Q5

-- UPDATE CHAP10HW_EMP
-- SET
-- WHERE;

SELECT * FROM CHAP10HW_EMP;

DELETE FROM CHAP10HW_EMP 
     WHERE EMPNO IN (SELECT E.EMPNO
                        FROM CHAP10HW_EMP E, CHAP10HW_SALGRADE S 
                        WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                        AND S.GRADE = 5
                    )
;
COMMIT;





              



-- Q5

 
 
SELECT * FROM CHAP10HW_EMP;



-- 트랜잭션
-- 하나의 단위로 데이터를 처리한다
-- 커밋 / 롤백


-- 세션







