
-- 13장 객체종류 //////////////////////////////////


-- 데이터사전
-- 인덱스 : 검색 성능 향상을 위해 사용

-- 뷰
-- 시퀀스 : 오라클에만 있음
-- 동의어 SYNONYM;
 
-- 14장 제약조건 //////////////////////////////////
-- 테이블 열에 저장될 데이터의 특성, 조건을 지정 
-- NOT NULL	    지정한 열에 NULL을 허용하지 않습니다. NULL을 제외한 데이터의 중복은 허용됩니다.
-- UNIQUE	    지정한 열이 유일한 값을 가져야 합니다. 즉 중복될 수 없습니다. 단 NULL은 값의 중복에서 제외됩니다.
-- PRIMARY KEY	지정한 열이 유일한 값이면서 NULL을 허용하지 않습니다. PRIMARY KEY는 테이블에 하나만 지정 가능합니다.
-- FOREIGN KEY	다른 테이블의 열을 참조하여 존재하는 값만 입력할 수 있습니다.
-- CHECK	    설정한 조건식을 만족하는 데이터만 입력 가능합니다.


-- 실습
CREATE TABLE TABLE_NOTNULL(
    LOGIN_ID VARCHAR2(20) NOT NULL,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL     VARCHAR2(20)
);

DESC TABLE_NOTNULL;
SELECT * FROM TABLE_NOTNULL;

INSERT INTO TABLE_NOTNULL (LOGIN_ID, LOGIN_PWD, TEL)
VALUES ('TEST_ID_01',NULL,'010-1234-5678');
INSERT INTO TABLE_NOTNULL (LOGIN_ID, LOGIN_PWD, TEL)
VALUES ('TEST_ID_01',1234,'010-1234-5678');

ALTER TABLE TABLE_NOTNULL
MODIFY (TEL NOT NULL);

-- NOT NULL : NULL 안돼. 값 있어야해. 필수값


-- UNIQUE : 
-- 지정된 열에 중복 데이터 저장 불가
-- NULL 저장은 가능 (단, 여러 개의 NULL 값 허용 여부는 특정 DBMS에 따라 다를 수 있음)


CREATE TABLE TABLE_UNIQUE(
    LOGIN_ID VARCHAR2(20) UNIQUE,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL     VARCHAR2(20)
);

INSERT INTO TABLE_UNIQUE (LOGIN_ID, LOGIN_PWD, TEL)
VALUES ('TEST_ID_01','PWD01','010-1234-5678');


INSERT INTO TABLE_UNIQUE (LOGIN_ID, LOGIN_PWD, TEL)
VALUES ('TEST_ID_02','PWD01','010-1234-5678');



INSERT INTO TABLE_UNIQUE (LOGIN_ID, LOGIN_PWD, TEL)
VALUES (NULL,'PWD01','010-1234-5678');

UPDATE TABLE_UNIQUE
   SET LOGIN_ID = 'TEST_ID_03'
WHERE LOGIN_ID IS NULL;

ALTER TABLE TABLE_UNIQUE
MODIFY(TEL UNIQUE);

UPDATE TABLE_UNIQUE
   SET TEL = NULL
WHERE LOGIN_ID IN ('TEST_ID_01', 'TEST_ID_02');

-- 열 추가
ALTER TABLE TABLE_UNIQUE
    ADD ETC VARCHAR2(20); 

SELECT * FROM TABLE_UNIQUE;

-- PRIMARY KEY////////////////////////////
CREATE TABLE TABLE_PK(
    LOGIN_ID VARCHAR2(20) PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL     VARCHAR2(20)
); 

SELECT * FROM TABLE_PK;


-- FOREIGN KEY////////////////////////////
CREATE TABLE TABLE_FK(
    DEPTNO  NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
    DNAME   VARCHAR2(14),
    LOC     VARCHAR2(13)
); 

SELECT * FROM TABLE_FK;

CREATE TABLE EMP_PK(
    EMPNO   NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
    ENAME   VARCHAR2(10),
    JOB     VARCHAR2(9),
    MGR     NUMBER(4),
    HIREDATE    DATE,
    SAL     NUMBER(7,2),
    COMM    NUMBER(7,2),
    DEPTNO  NUMBER(2) CONSTRAINT EMPFK_EMPNO_FK REFERENCES TABLE_FK (DEPTNO)
); 

 
INSERT INTO EMP_PK
VALUES(999, 'TEST_NAME', 'TEST_JOB', NULL, TO_DATE('2001/01/01','YYYY/MM/DD'), 3000, NULL, 10);


INSERT INTO TABLE_FK
VALUES(10, 'TEST_NAME', 'TEST_LOC');

SELECT * FROM TABLE_FK;

INSERT INTO EMP_PK
VALUES(999, 'TEST_NAME', 'TEST_JOB', NULL, TO_DATE('2001/01/01','YYYY/MM/DD'), 3000, NULL, 10);

SELECT * FROM EMP_PK;


DELETE FROM TABLE_FK
WHERE DEPTNO = 10;




CREATE TABLE TABLE_CHECK(
    LOGIN_ID    VARCHAR2(20) CONSTRAINT TBLCK_LOGINID_PK PRIMARY KEY,
    LOGIN_PWD   VARCHAR2(20) CONSTRAINT TBLCK_LOGINPW_CK CHECK (LENGTH(LOGIN_PWD) > 3),
    TEL         VARCHAR2(20)
); 
SELECT * FROM TABLE_CHECK;

INSERT INTO TABLE_CHECK
VALUES('TEST_ID', '1234', '010-1234-5678');



-- DEFAULT





-- 선생님이 가르쳐줌
-- 테이블정의서 
-- 오라클 테이블 정의서 쿼리
CREATE VIEW VW_SCOTT_TABLE
AS(

SELECT A.TABLE_NAME AS TABLE_NAME,
   A.TAB_CMT AS 테이블설명,
         A.COLUMN_NAME AS 컬럼명,
         B.POS AS PK,
         A.COL_CMT AS 컬럼설명,
         A.DATA_TYPE AS 데이터유형,
         A.데이터길이,
         A.NULLABLE AS NULL여부,
         A.COLUMN_ID AS 컬럼순서,
         A.DATA_DEFAULT AS 기본값
FROM
(SELECT S1.TABLE_NAME,
   S3.COMMENTS AS TAB_CMT,
         S1.COLUMN_NAME,
         S2.COMMENTS AS COL_CMT,
         S1.DATA_TYPE,
         CASE WHEN S1.DATA_PRECISION IS NOT NULL THEN DATA_PRECISION||','||DATA_SCALE
         ELSE TO_CHAR(S1.DATA_LENGTH)
         END  AS 데이터길이,
         NULLABLE,
         COLUMN_ID,
         DATA_DEFAULT
FROM  USER_TAB_COLUMNS S1,
         USER_COL_COMMENTS S2,
         USER_TAB_COMMENTS S3
WHERE S1.TABLE_NAME = S2.TABLE_NAME
   AND S1.COLUMN_NAME = S2.COLUMN_NAME
   AND S2.TABLE_NAME = S3.TABLE_NAME ) A,        
(SELECT T1.TABLE_NAME, T2.COLUMN_NAME, 'PK'||POSITION AS POS
   FROM (SELECT TABLE_NAME, CONSTRAINT_NAME  
              FROM USER_CONSTRAINTS
                  WHERE  CONSTRAINT_TYPE = 'P' )T1,
                  (SELECT TABLE_NAME, CONSTRAINT_NAME,  COLUMN_NAME, POSITION
                 FROM USER_CONS_COLUMNS ) T2
          WHERE T1.TABLE_NAME = T2.TABLE_NAME
             AND T1.CONSTRAINT_NAME = T2.CONSTRAINT_NAME  ) B
WHERE A.TABLE_NAME = B.TABLE_NAME(+)
   AND A.COLUMN_NAME = B.COLUMN_NAME(+)    
ORDER BY A.TABLE_NAME,  A.COLUMN_ID 

);


-- 되새김문제 386P
CREATE TABLE DEPT_CONST(
    DEPTNO  NUMBER(2)       CONSTRAINT DEPTCONST_DEPTNO_PK PRIMARY KEY,
    DNAME   VARCHAR2(14)    CONSTRAINT DEPTCONST_DNAME_UNG UNIQUE,
    LOC     VARCHAR2(13)    CONSTRAINT DEPTCONST_LOC_NN NOT NULL
);   

SELECT * FROM DEPT_CONST;

CREATE TABLE EMP_CONST(
    EMPNO    NUMBER(4)      CONSTRAINT EMPCONST_EMPNO_PK PRIMARY KEY,
    ENAME    VARCHAR2(10)   CONSTRAINT EMPCONST_ENAME_NN NOT NULL      ,
    JOB      VARCHAR2(9)                                              ,    
    TEL      VARCHAR2(20)   CONSTRAINT EMPCONST_TEL_UNG UNIQUE     ,
    HIREDATE DATE                                                     ,
    SAL      NUMBER(7,2)    CHECK (SAL BETWEEN 1000 AND 9999)             ,
    COMM     NUMBER(7,2)                                              ,
    DEPTNO   NUMBER(2)    CONSTRAINT EMPCONST_DEPTNO_FK REFERENCES TABLE_FK (DEPTNO) 
);   

SELECT * FROM EMP_CONST;



-- CREATE VIEW VW_CONST
--     AS ( 
--         SELECT 
--               TABLE_NAME
--             , CONSTRAINT_NAME
--             , CONSTRAINT_TYPE
--         FROM EMP_CONST E
--         UNION ALL
--         SELECT 
--               TABLE_NAME
--             , CONSTRAINT_NAME
--             , CONSTRAINT_TYPE
--         FROM DEPT_CONST D;
--     );

 SELECT * FROM VW_CONST;  

CREATE VIEW VW_CONST_TEST
AS(
    SELECT 
        TABLE_NAME
        , CONSTRAINT_NAME
        , CONSTRAINT_TYPE
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'EMP_CONST' OR TABLE_NAME = 'DEPT_CONST' 
);